
development:
   adapter: postgresql
   encoding: unicode
   database: map_isra_development
   pool: 5
   username: map_isra
   password: 121788gloriA
   timeout: 5000
   host: localhost



production:
   adapter: postgresql
   encoding: unicode
   database: map_isra_production
   pool: 5
   username: map_isra
   password: 121788gloriA
   timeout: 5000
   host: localhost
